"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-30

Hand-written rather than autogenerated so the first migration is reviewable and
reproducible without a live database.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# `create_type=False` matters: the types are created explicitly at the top of
# upgrade(), and without this SQLAlchemy emits a second CREATE TYPE when it
# builds the first table that references one. The failure reads as
# 'type "role" already exists' and aborts the migration.
role = postgresql.ENUM(
    "OWNER", "EDITOR", "VIEWER", name="role", create_type=False
)
ai_task_type = postgresql.ENUM(
    "GENERATE_DESIGN", "GENERATE_SPEC", name="ai_task_type", create_type=False
)
ai_task_status = postgresql.ENUM(
    "QUEUED", "RUNNING", "COMPLETED", "FAILED", name="ai_task_status", create_type=False
)


def upgrade() -> None:
    role.create(op.get_bind(), checkfirst=True)
    ai_task_type.create(op.get_bind(), checkfirst=True)
    ai_task_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "user",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("clerk_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String()),
        sa.Column("image_url", sa.String()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_user_clerk_id", "user", ["clerk_id"], unique=True)
    op.create_index("ix_user_email", "user", ["email"])

    op.create_table(
        "project",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text()),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_project_owner_id", "project", ["owner_id"])

    op.create_table(
        "project_member",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", role, server_default="VIEWER", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "user_id", name="uq_project_member"),
    )
    op.create_index("ix_project_member_project_id", "project_member", ["project_id"])
    op.create_index("ix_project_member_user_id", "project_member", ["user_id"])

    op.create_table(
        "project_invite",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", role, server_default="VIEWER", nullable=False),
        sa.Column("invited_by_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["invited_by_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "email", name="uq_project_invite"),
    )
    op.create_index("ix_project_invite_email", "project_invite", ["email"])

    op.create_table(
        "chat_message",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String()),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_message_project_created",
        "chat_message",
        ["project_id", "created_at"],
    )

    op.create_table(
        "snapshot",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("blob_url", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_snapshot_project_created", "snapshot", ["project_id", "created_at"]
    )

    op.create_table(
        "ai_task",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(), nullable=False),
        sa.Column("type", ai_task_type, nullable=False),
        sa.Column("status", ai_task_status, server_default="QUEUED", nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text())),
        sa.Column("triggerdev_id", sa.String()),
        sa.Column("error", sa.Text()),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ai_task_project_created", "ai_task", ["project_id", "created_at"])
    op.create_index("ix_ai_task_status", "ai_task", ["status"])


def downgrade() -> None:
    op.drop_index("ix_ai_task_status", table_name="ai_task")
    op.drop_index("ix_ai_task_project_created", table_name="ai_task")
    op.drop_table("ai_task")

    op.drop_index("ix_snapshot_project_created", table_name="snapshot")
    op.drop_table("snapshot")

    op.drop_index("ix_chat_message_project_created", table_name="chat_message")
    op.drop_table("chat_message")

    op.drop_index("ix_project_invite_email", table_name="project_invite")
    op.drop_table("project_invite")

    op.drop_index("ix_project_member_user_id", table_name="project_member")
    op.drop_index("ix_project_member_project_id", table_name="project_member")
    op.drop_table("project_member")

    op.drop_index("ix_project_owner_id", table_name="project")
    op.drop_table("project")

    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_clerk_id", table_name="user")
    op.drop_table("user")

    ai_task_status.drop(op.get_bind(), checkfirst=True)
    ai_task_type.drop(op.get_bind(), checkfirst=True)
    role.drop(op.get_bind(), checkfirst=True)